"""changed user_session back to session

Revision ID: 152ec7d44a6d
Revises: aaf237ce2d08
Create Date: 2024-05-22 12:46:14.748709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152ec7d44a6d'
down_revision = 'aaf237ce2d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meditation_id', sa.Integer(), nullable=False),
    sa.Column('journal_entry', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meditation_id'], ['meditations.id'], name=op.f('fk_sessions_meditation_id_meditations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('meditation_id', sa.INTEGER(), nullable=False),
    sa.Column('journal_entry', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['meditation_id'], ['meditations.id'], name='fk_user_sessions_meditation_id_meditations'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_sessions_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sessions')
    # ### end Alembic commands ###
