"""add images to meditation cards

Revision ID: 49cd475eeb97
Revises: 152ec7d44a6d
Create Date: 2024-05-23 13:54:54.791663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cd475eeb97'
down_revision = '152ec7d44a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meditations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meditations', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
