"""Add favorite model

Revision ID: 535576aecbd0
Revises: fd6455e3b7ef
Create Date: 2024-05-29 03:08:59.906357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535576aecbd0'
down_revision = 'fd6455e3b7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meditation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meditation_id'], ['meditations.id'], name=op.f('fk_favorites_meditation_id_meditations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
